name: Deploy Employee Training Application

on:
  push:
    branches:
      - master
    tags:
      - "v*-hello-world"
  pull_request:
    branches:
      - 'master'

jobs:
  deploy-docker-hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and Push Image
        run: |
            echo "${{ secrets.DOCKER_PWD }}" | docker login -u "kousikv" --password-stdin
            docker image build -t kousikv/kousik_v1:latest
            docker push kousikv/kousik_v1:latest